language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: "gFX0QjxbaLCBAmh7FEJocn/oA4b7jXBhEAJUb3gs3W96CN4nhu6iUMS7+WKJeMPodXNmUtKFtkz0QoR9RUC16bwo85sx+mLgDiDWivEbz+U3/l6pOtRmKIexN7wb90GH7QLZm7e9xzOFiVm4PAvK9SGvqVq7yMKLmqr1/jGRll7kOPqJZycCwDPBqO2Jj/PliyTyx0P0dd9G/XwSd38mNRb31uRiVKZ2/pcgkmteAH3ncFRPlPC2NVERqhQpE/5mXGhddNkg+h7H1w2DpJvkwUcbc8ruFhx0vDkPvGGNnx5+sBjStH9lUq1OCF75/j7TuJ4Pu4Uh3jZxEUXn3er+eSqnLoot/1rt9DmkO4MC5DliGAC8XpfdN6XLocMl8mYW2hgwQjLlo4oYWJDIudRWrVafJewK4vvlQhoLrOB1AsOX075HoZBD+nJ/9pCuzr3sc314Fd0zV/hH9JwDXNe/sRTLXGk7hvm6XD3a8uQjprvbx6dUVYPA1eIwr3SuXP9/aj7X+bYtcCusItqyTwHTcfyL1tZ4IvP3S9WGd0wGM+fKFummAP58uiAiJS7/9MjIZDpvGWOXMu+IXei5WTpyn1b1O550YenyfqERs6a9pGgj04QHf0vcC9vwZE4GThjQF4WIEAXFAzkyuGHas5m+q1fuP1AHiHdvN21m3FRP3Lg="
  - secure: "NGP6SR4w+/be/yU52w90yl4iN/b8omhzqe/1zAAqnrTr/0NRO9tmzQXJUNC2+VjPvgByw8/Dp0uv6vXx1U7bJd+CwhdgJZAZOn0XStmleI6Wxa9BNzrmlLpjxmojxkkecVl11elNMrODel2fV5oPMo2lWU9BlNy2CpYVp0cfqp0UaUykk1tl+FforIRT8yup4yRPjstSmGpu2OBW2lo4SU1ppjXiWKqThsiUAaiWMmF/P6B7TRo2xKfp2wyCAoN2E5BODqFlWuIIl5TQYTGSI1gINe5KtPiswyUGAzjJJM7WL6IjfFuB/xFcFhYmgqF37OBc3BLbmRiwR9ewPxayoUkmaVwYX8DdJEp+U0Yq5s2Uu2b8l0/sNd5guKHPDmisr0R/pR70QeMB0q2fH7bB80xUEfyt87uNn7qdKXsyZycqVA5c83RBfIVy7ipRDOWgeoZGW35klDBYpBfX9gF5ZFVdytXxES4wnijSEyjf/tstFIgN7l1wfZi/F88T6pMGHyAaGjeVuMlIcOsWNzJzMAyQwdEi828Nz6YyfV1/XydIrMEteWmOlMWyek6AHXK3P0Nnl59AlIEwt52vCvnVzyE6/uPF9kxrfpdnybQKcpNjvIxY0A5O5SMHKzG/aDSiKPL2SNgv+/D4i4VE0Sykvy6P7OaBOGFFNaikEq5S1js="
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: "EaK3HBdHEycF9pb3GOrVpr879WdsqG2l4t7JWvNJCIJgMqkKE5NF7b5Ye/7p2vBoc+mVY586b5e1Va4tJdwzgEjGANNFMC8TjAzsSJQ4uV4Xx82PBBIRpq0Jzaa5cGQY838mjp6H6sa3tHNeAcJpFr8EqW9wRBhDvsU0UZ+wE55yUc9s+SdnvI3/SpZnvGpB9jd1HDZ2GdOFAHt5suVmNWb2u6xV1/op7LzF1dWkt/nigENriHKmSBHvdHaXb42irqrtBa8cu+3vc26OLxrT7gYi+QDAXqD8zOSD83HfTHl8O1aL+jTCZghtNMxliZ3CiFjrZFs2hjPF2gwcAuWAin4Pi228nqJpTbhqomjmIT3QTmlT1Pin76U9+5aCQINCoavkUL1DcWA1Pm0/N6BHItXIvdxCobn3kIj1TfC5BcZqIp7LW29Pj8mj/DPd9ef0YBHSlt4+ts7Kf+M2h/yFDj61e1+lofpM45sPV3HRgVTWKJ8mMIFHuWe6qkLIhS7I1Hj+SbGrUWbGgfM9T4uh6mTT45Xes007bI9aThSozaOWDBxjVHYDEfU8T5SO1DfEU2C8ABF6esnoQjWlRwWM20VhO1B5TTQMmwS1IUj+OFQkjSWgaxxMn3lZszKLV7WZ5qweyHIYz2VMPZYHJ6qQa//8CuwzmB4srMaIiYYWJeE="
  on:
    branch: master
    repo: plepers/nanogl-sync
